### ISSUE TITLE
TIME_SERIES_INTRADAY

### ISSUE THREAD

**Issue by mdancho84** [business-science/alphavantager#1]
Alpha Vantage is updating sources for the intraday data. They hope to have the time series intraday source fixed within 2 weeks. Until then, the source will not be available.

**Comment by mdancho84** [comment]
Alpha Vantage fixed the issue.

**Comment by kvekka** [comment]
I'm using the following commands with the objective to obtain real time data. The scrip is listed in [BSE](https://www.bseindia.com/). I am able to obtain previous days' data at the specified intervals but not the real time data or even the interval data for the current day. Am I missing something here?

av_api_key(MY_API_KEY)
av_get(symbol = 'SBIN.BO', av_fun = "TIME_SERIES_INTRADAY", interval = "15min", outputsize = "full")

Thanks for your help.
