### ISSUE TITLE
Error <!DOCTYPE html>

### ISSUE THREAD

**Issue by Jmarks199** [business-science/alphavantager#2]
Hello, 

I receive an error message each time I make a call to the API, no matter what symbol or function I use.

I set my API key
`av_api_key("my_api_key")`

Then I make a call to the API
`SPY <- av_get("SPY", av_fun = "TIME_SERIES_DAILY_ADJUSTED")`

The code runs and it appears as though the API call will be succesful, however the following error message is printed to the console:

> Error:
> !DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>

Any resolution to this issue would be helpful. I have not made any system changes or updates that i believe affected the package, and it was working perfectly before.

Thanks

**Comment by DavisVaughan** [comment]
I don't think it it us. Even going to their demo page throws the same error. Maybe try again tomorrow? They might be doing maintenance. Thanks for bringing it up though.

Demo page:

https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=MSFT&interval=1min&apikey=demo

Update: Even their home page is down. https://www.alphavantage.co/

**Comment by mdancho84** [comment]
It seems to be working now.
```
> alphavantager::av_get("SPY", av_fun = "TIME_SERIES_DAILY_ADJUSTED")
# A tibble: 100 x 9
    timestamp   open   high    low  close adjusted_close   volume dividend_amount
       <date>  <dbl>  <dbl>  <dbl>  <dbl>          <dbl>    <int>           <dbl>
 1 2017-05-24 240.32 240.73 239.93 240.61       238.2620 49181099               0
 2 2017-05-25 241.20 242.08 240.96 241.76       239.4008 64071661               0
 3 2017-05-26 241.54 241.90 241.45 241.71       239.3513 46629905               0
 4 2017-05-30 241.34 241.79 241.16 241.50       239.1434 35201897               0
 5 2017-05-31 241.84 241.88 240.64 241.44       239.0840 91796016               0
 6 2017-06-01 241.97 243.38 241.64 243.36       240.9852 68962024               0
 7 2017-06-02 243.42 244.35 243.08 244.17       241.7873 88666128               0
 8 2017-06-05 243.97 244.30 243.76 243.99       241.6091 44698825               0
 9 2017-06-06 243.34 243.98 243.12 243.21       240.8367 50375430               0
10 2017-06-07 243.60 243.92 242.83 243.66       241.2823 54144311               0
# ... with 90 more rows, and 1 more variables: split_coefficient <dbl>
```
