### ISSUE TITLE
Consider `skip_on_cran()` in addition to `skip_if_no_auth()`

### ISSUE THREAD

**Issue by lionel-** [business-science/alphavantager#8]
alphavantager shows up in the revdep checks of purrr 0.3.1 (https://github.com/tidyverse/purrr/blob/42505ed6cd24a795421a538bb1849cd41d66b627/revdep/problems.md#alphavantager):

```
Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day.
```

IIUC, some tests do pass before the rate limit is hit, and then revdepcheck detect a change in the failures. Using `skip_on_cran()` would help consistently skipping the tests.

**Comment by mdancho84** [comment]
Awesome @lionel- !! That will help big time.

**Comment by romainfrancois** [comment]
Same problem for the revdepcheck of `dplyr` https://github.com/tidyverse/dplyr/issues/4265
